version: '3.8'
services:
  db:
    image: mariadb:10.7.3
    environment:
      MYSQL_ROOT_PASSWORD: dev123
      MYSQL_DATABASE: web

  redis:
    image: redis:6.2.7

  app:
    build: .
    image: workshop-laravel:local
    pull_policy: always
    environment:
      PHP_OPCACHE_ENABLE: 0
      PHP_XDEBUG_ENABLE: 0
      PHP_XDEBUG_START_WITH_REQUEST: "trigger"
      PHP_XDEBUG_MODE: "develop,debug"
      AUTOSTART_MIGRATIONS: 0
      AUTOSTART_QUEUE: 0
      AUTOSTART_WEBSOCKETS: 0
    ports:
      - '3000:3000/tcp'
    dns:
      - 8.8.8.8
      - 8.8.4.4
